---

require:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.2

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Max: 120
